@FernandezA_MiniChallenge_2_4Again_Endpoints__HostAddress = http://localhost:5172

GET {{FernandezA_MiniChallenge_2_4Again_Endpoints__HostAddress}}/weatherforecast/
Accept: application/json

###
